//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsconPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CajaLog
    {
        public long CajaLogID { get; set; }
        public long CajaID { get; set; }
        public long TransaccionID { get; set; }
        public long EmpleadoID { get; set; }
        public double Monto { get; set; }
        public string Fecha { get; set; }
        public string Hora { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual Transacciones Transacciones { get; set; }
        public virtual Cajas Cajas { get; set; }
    }
}
