//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsconPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuraciones
    {
        public long ConfiguracionID { get; set; }
        public long CajaID { get; set; }
        public string Configuracion { get; set; }
        public string Valor { get; set; }
        public string AgregadoEl { get; set; }
        public long AgregadoPor { get; set; }
        public string ModificadoEl { get; set; }
        public Nullable<long> ModificadoPor { get; set; }
    
        public virtual Empleados EmpleadoAdd { get; set; }
        public virtual Empleados EmpleadoUpd { get; set; }
    }
}
