//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsconPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresas()
        {
            this.Documentos = new HashSet<Documentos>();
            this.Empleados = new HashSet<Empleados>();
        }
    
        public long EmpresaID { get; set; }
        public long IdentificacionID { get; set; }
        public string NroDocIdent { get; set; }
        public string NombreComercial { get; set; }
        public string RazonSocial { get; set; }
        public string Direccion { get; set; }
        public long DistritoID { get; set; }
        public string Urbanizacion { get; set; }
        public string NroTelefonico { get; set; }
        public string CorreoElectronico { get; set; }
        public string AgregadoEl { get; set; }
        public long AgregadoPor { get; set; }
        public string ModificadoEl { get; set; }
        public Nullable<long> ModificadoPor { get; set; }
    
        public virtual Distritos Distritos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentos> Documentos { get; set; }
        public virtual Empleados EmpleadoUpd { get; set; }
        public virtual Empleados EmpleadoAdd { get; set; }
        public virtual Identificaciones Identificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleados> Empleados { get; set; }
    }
}
